### ISSUE TITLE
gdalheaders todo (pre-alpha)

### ISSUE THREAD

**Issue by mdsumner** [mdsumner/dirigible#3]
Brought out from #2 

- [ ] field values needs more types (updated allocate_list, compare field read and field report)
- [x] need to remove duplication,  ExecuteSQL, extent filter, feature count, etc. 
- [x] do we need CollectorList.h now, relation to countfeatures (note use of bForce now not iteration)
- [x] sort out metadata files on windows and white zone envvars stuff generally
- [x] make function count_features for an open layer, to force count by iteration - and make it do everything, hide all the ResetReading(), check the GetFeatureCount(false), GetFeatureCount(true), then iterate

**Comment by mdsumner** [comment]
Cleaned up ExecuteSQL, extent filter and feature count - added `gdal_layer()` which removes a bunch of duplication, and feature count now always forces.

**Comment by mdsumner** [comment]
Have to back out the count stuff, because OSM and others don't provide a count without iteration.
